"Resource\HL2MMod_Gameplay_Options.res"
{
	////////////////////////////////
	// HPH -> MMOD compatibility: //
	////////////////////////////////
	"FakeButton1"
	{
		"ControlName"  "Button"
		"fieldName"    "FakeButton1"
		"xpos"         "340"
		"ypos"         "216"
		"zpos"         "0"
		"wide"         "170"
		"tall"         "135"
		"autoResize"   "0"
		"pinCorner"    "0"
		"visible"      "1"
		"enabled"      "0"
		"tabPosition"  "0"
		"labelText"    ""
		"Default"      "0"
	}

	"Lbl_HL2MModSpreadTypeDescription"
	{
		"ControlName"    "Label"
		"fieldName"      "Lbl_HL2MModSpreadTypeDescription"
		"xpos"           "346"
		"ypos"           "202"
		"zpos"           "1"
		"wide"           "160"
		"tall"           "160"
		"visible"        "1"
		"enabled"        "1"
		"autoResize"     "0"
		"pinCorner"      "0"
		"tabPosition"    "0"
		"labelText"      "#GameUI_HL2MModSpreadTypeDescription"
		"textAlignment"  "west"
		"dulltext"       "1"
		"brighttext"     "0"
		"Font"           "DefaultSmall"
		"wrap"           "1"
	}

	"FakeButton2"
	{
		"ControlName"  "Button"
		"fieldName"    "FakeButton2"
		"xpos"         "340"
		"ypos"         "467"
		"zpos"         "0"
		"wide"         "170"
		"tall"         "105"
		"autoResize"   "0"
		"pinCorner"    "0"
		"visible"      "1"
		"enabled"      "0"
		"tabPosition"  "0"
		"labelText"    ""
		"Default"      "0"
	}

	"Lbl_HL2MModFlashlightModeDescription"
	{
		"ControlName"    "Label"
		"fieldName"      "Lbl_HL2MModFlashlightModeDescription"
		"xpos"           "350"
		"ypos"           "470"
		"zpos"           "1"
		"wide"           "128"
		"tall"           "100"
		"visible"        "1"
		"enabled"        "1"
		"autoResize"     "0"
		"pinCorner"      "0"
		"tabPosition"    "0"
		"labelText"      "#GameUI_HL2MModFlashlightModeDescription"
		"textAlignment"  "west"
		"dulltext"       "1"
		"brighttext"     "0"
		"Font"           "DefaultSmall"
		"wrap"           "1"
	}
	////////////////////////////////


	"HeadBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HeadBox"
		"xpos"		"20"
		"ypos"		"340"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"SndBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"SndBox"
		"xpos"		"20"
		"ypos"		"90"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"CrossBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"CrossBox"
		"xpos"		"525"
		"ypos"		"40"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"SpreadBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"SpreadBox"
		"xpos"		"340"
		"ypos"		"190"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"DecalsBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"DecalsBox"
		"xpos"		"20"
		"ypos"		"190"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"DecalsOnEverythingBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"DecalsOnEverythingBox"
		"xpos"		"20"
		"ypos"		"240"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ImmersiveCameraBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ImmersiveCameraBox"
		"xpos"		"20"
		"ypos"		"290"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ViewRollBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ViewRollBox"
		"xpos"		"525"
		"ypos"		"490"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ViewBreathingBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ViewBreathingBox"
		"xpos"		"525"
		"ypos"		"440"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HitMarkersBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HitMarkersBox"
		"xpos"		"525"
		"ypos"		"390"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HitFeedbackBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HitFeedbackBox"
		"xpos"		"525"
		"ypos"		"340"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"WeaponsPunchBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"WeaponsPunchBox"
		"xpos"		"525"
		"ypos"		"540"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ExplosivePropFireBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ExplosivePropFireBox"
		"xpos"		"525"
		"ypos"		"290"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HEVVoiceBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HEVVoiceBox"
		"xpos"		"525"
		"ypos"		"240"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"DynLightsBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"DynLightsBox"
		"xpos"		"20"
		"ypos"		"390"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"UseMuzzleForProjBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"UseMuzzleForProjBox"
		"xpos"		"20"
		"ypos"		"140"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"CombineEyesBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"CombineEyesBox"
		"xpos"		"20"
		"ypos"		"40"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ProjectileBulletsBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ProjectileBulletsBox"
		"xpos"		"20"
		"ypos"		"440"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"CombineBetterAimBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"CombineBetterAimBox"
		"xpos"		"20"
		"ypos"		"490"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"DynLightsFromAflameBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"DynLightsFromAflameBox"
		"xpos"		"525"
		"ypos"		"90"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HealthRegenerationBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HealthRegenerationBox"
		"xpos"		"525"
		"ypos"		"190"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"DropClipBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"DropClipBox"
		"xpos"		"20"
		"ypos"		"540"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"SlowWhenIronsightedBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"SlowWhenIronsightedBox"
		"xpos"		"340"
		"ypos"		"140"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"KillSoundFeedbackBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"KillSoundFeedbackBox"
		"xpos"		"340"
		"ypos"		"90"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"NPCMoreFlinchBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"NPCMoreFlinchBox"
		"xpos"		"340"
		"ypos"		"40"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"IronsightModeBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"IronsightModeBox"
		"xpos"		"350"
		"ypos"		"390"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"FlashlightModeBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"FlashlightModeBox"
		"xpos"		"350"
		"ypos"		"440"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HeadLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HeadLabel"
		"xpos"		"20"
		"ypos"		"315"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModHeadBob"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"CrossLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"CrossLabel"
		"xpos"		"525"
		"ypos"		"15"
		"wide"		"100"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModCrosshair"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"SndLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SndLabel"
		"xpos"		"20"
		"ypos"		"65"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModStereo"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"SndWarningLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SndWarningLabel"
		"xpos"		"155"
		"ypos"		"83"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModStereoWarning"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"20"
		"ypos"		"115"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModUseMuzzleForProjectiles"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"20"
		"ypos"		"165"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModMoreBloodDecals"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"fieldName"		"Label3"
		"xpos"		"20"
		"ypos"		"215"
		"wide"		"150"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModDecalsOnEverything"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label4"
	{
		"ControlName"		"Label"
		"fieldName"		"Label4"
		"xpos"		"20"
		"ypos"		"265"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModImmersiveCamera"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label6"
	{
		"ControlName"		"Label"
		"fieldName"		"Label6"
		"xpos"		"20"
		"ypos"		"365"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModDynLights"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label8"
	{
		"ControlName"		"Label"
		"fieldName"		"Label8"
		"xpos"		"20"
		"ypos"		"15"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModCombineEyes"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label5"
	{
		"ControlName"		"Label"
		"fieldName"		"Label5"
		"xpos"		"551"
		"ypos"		"570"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModMapRestartWarning"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label9"
	{
		"ControlName"		"Label"
		"fieldName"		"Label9"
		"xpos"		"155"
		"ypos"		"33"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModCombineEyesLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label10"
	{
		"ControlName"		"Label"
		"fieldName"		"Label10"
		"xpos"		"155"
		"ypos"		"133"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModUseMuzzleForProjectilesLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label11"
	{
		"ControlName"		"Label"
		"fieldName"		"Label11"
		"xpos"		"155"
		"ypos"		"183"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModMoreBloodDecalsLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label12"
	{
		"ControlName"		"Label"
		"fieldName"		"Label12"
		"xpos"		"155"
		"ypos"		"233"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModDecalsOnEverythingLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label13"
	{
		"ControlName"		"Label"
		"fieldName"		"Label13"
		"xpos"		"155"
		"ypos"		"283"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModImmersiveCameraLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label14"
	{
		"ControlName"		"Label"
		"fieldName"		"Label14"
		"xpos"		"155"
		"ypos"		"333"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModCameraBobLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label15"
	{
		"ControlName"		"Label"
		"fieldName"		"Label15"
		"xpos"		"155"
		"ypos"		"383"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModDynLightsLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"13"
		"ypos"		"10"
		"wide"		"650"
		"tall"		"3"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Divider2"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider2"
		"xpos"		"660"
		"ypos"		"10"
		"wide"		"3"
		"tall"		"570"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Divider3"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider3"
		"xpos"		"12"
		"ypos"		"577"
		"wide"		"650"
		"tall"		"3"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Divider4"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider4"
		"xpos"		"11"
		"ypos"		"10"
		"wide"		"3"
		"tall"		"570"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Label17"
	{
		"ControlName"		"Label"
		"fieldName"		"Label17"
		"xpos"		"20"
		"ypos"		"415"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModProjectileBullets"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label18"
	{
		"ControlName"		"Label"
		"fieldName"		"Label18"
		"xpos"		"155"
		"ypos"		"435"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModProjectileBulletsLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label19"
	{
		"ControlName"		"Label"
		"fieldName"		"Label19"
		"xpos"		"20"
		"ypos"		"465"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModCombineBetterAim"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label20"
	{
		"ControlName"		"Label"
		"fieldName"		"Label20"
		"xpos"		"155"
		"ypos"		"480"
		"wide"		"186"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModCombineBetterAimLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label21"
	{
		"ControlName"		"Label"
		"fieldName"		"Label21"
		"xpos"		"525"
		"ypos"		"65"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModAflameDynamicFire"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label22"
	{
		"ControlName"		"Label"
		"fieldName"		"Label22"
		"xpos"		"525"
		"ypos"		"114"
		"wide"		"128"
		"tall"		"42"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModAflameDynamicFireLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label23"
	{
		"ControlName"		"Label"
		"fieldName"		"Label23"
		"xpos"		"530"
		"ypos"		"155"
		"wide"		"160"
		"tall"		"30"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModRegeneration"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label25"
	{
		"ControlName"		"Label"
		"fieldName"		"Label25"
		"xpos"		"20"
		"ypos"		"515"
		"wide"		"256"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModDropClip"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label26"
	{
		"ControlName"		"Label"
		"fieldName"		"Label26"
		"xpos"		"155"
		"ypos"		"531"
		"wide"		"128"
		"tall"		"42"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModDropClipLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"DefaultSmall"
		"wrap"		"1"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label7"
	{
		"ControlName"		"Label"
		"fieldName"		"Label7"
		"xpos"		"525"
		"ypos"		"315"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModHitEffects"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label16"
	{
		"ControlName"		"Label"
		"fieldName"		"Label16"
		"xpos"		"525"
		"ypos"		"365"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModHitMarkers"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label27"
	{
		"ControlName"		"Label"
		"fieldName"		"Label27"
		"xpos"		"525"
		"ypos"		"415"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModViewIdle"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label28"
	{
		"ControlName"		"Label"
		"fieldName"		"Label28"
		"xpos"		"525"
		"ypos"		"465"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModViewRoll"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label29"
	{
		"ControlName"		"Label"
		"fieldName"		"Label29"
		"xpos"		"525"
		"ypos"		"515"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModWeaponPunch"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label30"
	{
		"ControlName"		"Label"
		"fieldName"		"Label30"
		"xpos"		"525"
		"ypos"		"265"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModExplosivePropsFire"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label24"
	{
		"ControlName"		"Label"
		"fieldName"		"Label24"
		"xpos"		"525"
		"ypos"		"215"
		"wide"		"150"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModHEVVoices"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"Font"		"Default"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label31"
	{
		"ControlName"		"Label"
		"fieldName"		"Label31"
		"xpos"		"340"
		"ypos"		"15"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModFlinch"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label32"
	{
		"ControlName"		"Label"
		"fieldName"		"Label32"
		"xpos"		"340"
		"ypos"		"65"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModKillFeedback"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label33"
	{
		"ControlName"		"Label"
		"fieldName"		"Label33"
		"xpos"		"340"
		"ypos"		"115"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModSlowIronsighted"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label34"
	{
		"ControlName"		"Label"
		"fieldName"		"Label34"
		"xpos"		"340"
		"ypos"		"165"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModSpreadType"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label36"
	{
		"ControlName"		"Label"
		"fieldName"		"Label36"
		"xpos"		"350"
		"ypos"		"365"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModIronsightMode"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"Label37"
	{
		"ControlName"		"Label"
		"fieldName"		"Label37"
		"xpos"		"350"
		"ypos"		"415"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_HL2MModFlashlightMode"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"98"
		"ypos"		"277"
		"wide"		"300"
		"tall"		"420"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
